groups:
- name: TEST-GROUP
  checks:
  - name: Google
    output:
      columns:
      - name: name
        width: 255
        align: LEFT
        content: "${name} - URL: ${url}" 
    host: www.google.de
    returnType: STRING
    checkExpression: STRING READ_VALUE <title>Google</title> CONTAINS
