@startuml

component service {

	component CheckService
	
	component MonitorService
	
	component XMLToMapConverter
	
	MonitorService -UP-> CheckService

}

component configuration {

	component ConfigurationReader
	
}

component console {

	component ConsoleRunner
	
	component ConsolePrinter
	
	ConsoleRunner -UP-> ConfigurationReader
	ConsoleRunner -UP-> ConsolePrinter
	ConsoleRunner -UP-> MonitorService

}

component swing {

	component SwingRunner
	
	SwingRunner -UP-> MonitorService
	SwingRunner -UP-> ConfigurationReader

}

@enduml