@startuml

component service {

	component CheckService
	
	component MonitorService
	
	component XMLToMapConverter
	
	MonitorService -UP-> CheckService

}

component console {

	component ConsoleRunner
	
	component ConfigurationReader
	
	component ConsolePrinter
	
	ConsoleRunner --> ConfigurationReader
	ConsoleRunner --> ConsolePrinter
	ConsoleRunner -UP-> MonitorService

}

component swing {

	component SwingRunner
	
	SwingRunner -UP-> MonitorService

}

@enduml