@startuml

actor User

node ServiceMonitor

node WebService1
node WebServiceN

interface "HTTP" as Interface1
interface "HTTP" as InterfaceN

User --> ServiceMonitor :Console or GUI

WebService1 -UP- Interface1
WebServiceN -UP- InterfaceN

ServiceMonitor --> Interface1
ServiceMonitor --> InterfaceN

@enduml